 LIST	P=16F887
 #include <p16f887.inc>
; CONFIG1
; __config 0x3FF7
 __CONFIG _CONFIG1, _FOSC_EXTRC_CLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF 
 
VALOR_C EQU 0x08
CONTADOR EQU 0X43
REST_1 EQU 0X30
REST_2 EQU 0X37
VALOR_P1 EQU 0X20
VALOR_P2 EQU 0X31
PUNTERO_1 EQU 0X40
PUNTERO_2 EQU 0X41
TEMP EQU 0X42
 
 ORG 0X00
 
INICIO
    MOVLW VALOR_C
    MOVWF CONTADOR
    MOVLW VALOR_P1
    MOVWF PUNTERO_1
    MOVLW VALOR_P2
    MOVWF PUNTERO_2

LOOP
    MOVF PUNTERO_1,W
    MOVWF FSR
    BTFSC INDF,6
    GOTO NUMERO
    GOTO LETRA
CONTINUO
    MOVWF TEMP
    MOVF PUNTERO_2,W
    MOVWF FSR
    MOVF TEMP,W
    MOVWF INDF
    INCF PUNTERO_1
    INCF PUNTERO_2
    DECFSZ CONTADOR
    GOTO LOOP
    SLEEP
       
NUMERO
    MOVLW REST_1
    SUBWF INDF,W
    GOTO CONTINUO
LETRA
    MOVLW REST_2
    SUBWF INDF,W
    GOTO CONTINUO
 
END
