LIST P=16F887
    #INCLUDE <P16F887.INC>
    
    CONTROL EQU 0X0C
    MAX EQU 0X193
    V_MAX EQU .30
    D_INICIAL EQU 0XBO
    ORG 0X00
    
INICIO
    BANKSEL TRISB
    MOVLW b'10011111' 
    MOVWF TRISB ; hago RB6 Y RB5 sean salidas
    
    BSF STATUS,RP1
    BSF STATUS,RP0
    BSF STATUS,IRP ;para moverme con INDF por los bancos 2 y 3 (necesito el 3)
    
REINICIO
    MOVLW D_INICIAL
    MOVWF FSR
    MOVLW V_MAX 
    MOVWF MAX
LOOP      
    MOVLW CONTROL
    SUBWF INDF,W
    BTFSC STATUS,C
    GOTO LED_ROJO
    GOTO LED_VERDE
CONTINUA
    BSF STATUS,IRP
    BSF STATUS,RP1
    BSF STATUS,RP0
    INCF FSR,F
    DECFSZ MAX,F
    GOTO LOOP
    GOTO REINICIO
    
LED_ROJO
    BANKSEL PORTB
    BSF PORTB,5
    CALL RET_2min
    BCF PORTB,5
    GOTO CONTINUA
LED_VERDE
    BANKSEL PORTB
    BSF PORTB,6
    CALL RET_2min
    BCF PORTB,6
    GOTO CONTINUA
	
    END

