LIST P=16F887
    #INCLUDE <P16F887.INC>
    
    CONTROL EQU .6
    MAX EQU 0X193
    V_MAX EQU .30
    D_INICIAL EQU 0X1B0
    TEMP EQU 0X193
    ORG 0X00
    
INICIO
    BANKSEL TRISB
    MOVLW b'10011111' 
    MOVWF TRISB ; hago RB6 Y RB5 sean salidas
    
    BSF STATUS,RP1
    BSF STATUS,RP0
    BSF STATUS,IRP ;para moverme con INDF por los bancos 2 y 3 (necesito el 3)
    
REINICIO
    MOVLW D_INICIAL
    MOVWF FSR
    MOVLW V_MAX 
    MOVWF MAX
LOOP
    MOVF INDF,W
    CALL TABLA
    MOVWF TEMP
    MOVLW CONTROL
    SUBWF TEMP,F
    BTFSC STATUS,C
    GOTO LED_ROJO
    GOTO LED_VERDE
CONTINUA
    BSF STATUS,RP1
    BSF STATUS,RP0
    INCF FSR,F
    DECFSZ MAX,F
    GOTO LOOP
    GOTO REINICIO
    
LED_ROJO
    BANKSEL PORTB
    BSF PORTB,5
    CALL RET_2min
    BCF PORTB,5
    GOTO CONTINUA
LED_VERDE
    BANKSEL PORTB
    BSF PORTB,6
    CALL RET_2min
    BCF PORTB,6
    GOTO CONTINUA
TABLA
    ADDWF PCL,F ;llega valor en aiken devuelvo en decimal
	NOP
	NOP
	NOP
	RETLW 0X00 
	RETLW 0X01 
	RETLW 0X02
	RETLW 0X03
	RETLW 0X04
	NOP 
	NOP
	NOP
	RETLW 0X05
	RETLW 0X06
	RETLW 0X07
	RETLW 0X08
	RETLW 0X09	
    END

